#!/usr/bin/env bash
set -euo pipefail

bin="${NIXOS_KEXEC_BIN:?NIXOS_KEXEC_BIN must point at nixos-kexec}"
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

spec="$tmpdir/disk-nix-install.json"
flake_source="$tmpdir/flake-source"
system="$tmpdir/system"
kernel="$tmpdir/bzImage"
initrd="$tmpdir/initrd"
script="$tmpdir/nixos-kexec.sh"
plan_json="$tmpdir/plan.json"
installer_plan_json="$tmpdir/installer-plan.json"
authorized_key="$tmpdir/id_ed25519.pub"
network_profiles="$tmpdir/network-profiles.json"
host_key="$tmpdir/ssh_host_ed25519_key"
known_hosts="$tmpdir/known_hosts"

printf '{"version":1,"apply":{"mode":"install"}}\n' >"$spec"
mkdir -p "$flake_source"
mkdir -p "$system"
printf '{}\n' >"$flake_source/flake.nix"
printf 'kernel\n' >"$kernel"
printf 'initrd\n' >"$initrd"
printf 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITest nixos-kexec-test\n' >"$authorized_key"
printf '{"home":{"connection":{"id":"home","type":"wifi"}}}\n' >"$network_profiles"
printf 'private-host-key\n' >"$host_key"
printf 'public-host-key\n' >"$host_key.pub"
printf 'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITest\n' >"$known_hosts"
cat >"$tmpdir/kexec-boot" <<'EOF'
#!/usr/bin/env bash
kexec --load ./bzImage \
  --initrd=./initrd \
  --command-line "init=/nix/store/example-system/init console=ttyS0 panic=1"
EOF

"$bin" --help | grep -F 'Deploy NixOS through kexec with disk-nix storage management' >/dev/null
"$bin" completions bash | grep -F 'nixos-kexec' >/dev/null

"$bin" installer plan \
  --authorized-key-file "$authorized_key" \
  --network-manager-profiles-json "$network_profiles" \
  --out-link "$tmpdir/kexec-tree" \
  --json >"$installer_plan_json"

jq -e '
  .system == "x86_64-linux"
  and .authorizedKeyCount == 1
  and .networkManagerProfilesJson == "'"$network_profiles"'"
  and .outLink != null
  and (.argv | any(. == "--impure"))
  and (.expression | contains("examples/kexec-installer.nix"))
  and (.expression | contains("builtins.fromJSON"))
  and (.expression | contains("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITest"))
' "$installer_plan_json" >/dev/null

if "$bin" installer build \
  --authorized-key-file "$authorized_key" 2>"$tmpdir/installer-build-refusal.err"; then
  echo "installer build without --execute unexpectedly succeeded" >&2
  exit 1
fi
grep -F 'installer build refuses to run without --execute' \
  "$tmpdir/installer-build-refusal.err" >/dev/null

if "$bin" installer plan 2>"$tmpdir/installer-key-refusal.err"; then
  echo "installer plan without an authorized key unexpectedly succeeded" >&2
  exit 1
fi
grep -F 'requires at least one --authorized-key-file or --authorized-key' \
  "$tmpdir/installer-key-refusal.err" >/dev/null

if [ -n "${NIXOS_KEXEC_EXAMPLES_DIR:-}" ]; then
  "${NIXOS_KEXEC_BASH:-bash}" -n "$NIXOS_KEXEC_EXAMPLES_DIR/install-from-template.sh"
  "${NIXOS_KEXEC_BASH:-bash}" -n "$NIXOS_KEXEC_EXAMPLES_DIR/install-with-preinstalled-disk-nix.sh"
  jq -e '.version == 1' "$NIXOS_KEXEC_EXAMPLES_DIR/specs/simple-root.json" >/dev/null
  jq -e '.version == 1 and .pools.zroot.operation == "create"' \
    "$NIXOS_KEXEC_EXAMPLES_DIR/specs/zfs-encrypted-root.by-id.json" >/dev/null
fi

"$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --ssh-option StrictHostKeyChecking=accept-new \
  --json >"$plan_json"

jq -e '
  .target == "root@192.0.2.10"
  and .flake == "github:example/flake#host"
  and .forceKexec == false
  and .installStrategy == "installer-builds-flake"
  and (.installStrategySummary | contains("installer evaluates the flake"))
  and (.commands | length == 10)
  and (.commands | any(.phase == "preflight" and (.argv | any(contains("NIXOS_KEXEC_REMOTE_IS_INSTALLER=0")))))
  and (.commands | any(.phase == "kexec" and .mutates == true and (.argv | any(contains("kexec -l")))))
  and (.commands | any(.phase == "kexec" and .mutates == true and (.argv | any(contains("kexec -e")))))
  and (.commands | all(.phase != "kexec" or (.argv | all(contains("systemctl kexec") | not))))
  and (.commands | any(.phase == "disk-nix-apply" and (.argv | any(contains("apply --spec")))))
  and (.commands | any(.phase == "nixos-install" and (.argv | any(contains("install nixos")))))
  and (.warnings | any(contains("kexec replaces the running kernel")))
  and (.warnings | any(contains("no system closure is copied by nixos-kexec")))
' "$plan_json" >/dev/null

"$bin" script root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --script-out "$script"

test -x "$script"
grep -F 'Generated by nixos-kexec' "$script" >/dev/null
grep -F 'NIXOS_KEXEC_FORCE_KEXEC=0; export NIXOS_KEXEC_FORCE_KEXEC' "$script" >/dev/null
grep -F 'INSTALL STRATEGY: installer evaluates the flake' "$script" >/dev/null
grep -F 'already in installer; skipping load and enter' "$script" >/dev/null
grep -F 'kexec -l /tmp/nixos-kexec/kexec/kernel' "$script" >/dev/null
grep -F 'sync; kexec -e' "$script" >/dev/null
grep -F '[ "$status" -eq 255 ] || [ "$status" -eq 124 ]' "$script" >/dev/null
if grep -F 'systemctl kexec' "$script" >/dev/null; then
  echo "script unexpectedly uses systemctl kexec" >&2
  exit 1
fi
grep -F 'init=/nix/store/example-system/init console=ttyS0 panic=1' "$script" >/dev/null
grep -F 'disk-nix-install.json --probe-current --execute' "$script" >/dev/null
grep -F 'install nixos --spec /tmp/nixos-kexec/disk-nix-install.json' "$script" >/dev/null

"$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --force-kexec \
  --json >"$plan_json"

jq -e '
  .forceKexec == true
  and (.commands | any(.phase == "preflight" and (.argv | any(contains("force-kexec requested")))))
  and (.commands | any(.phase == "stage-kexec" and (.argv | any(contains("NIXOS_KEXEC_FORCE_KEXEC:-0")))))
' "$plan_json" >/dev/null

"$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --flake-source "$flake_source" \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --ssh-tty \
  --disk-nix-command /run/current-system/sw/bin/disk-nix \
  --no-final-reboot \
  --json >"$plan_json"

jq -e '
  .diskNixCommand == "/run/current-system/sw/bin/disk-nix"
  and .sshTty == true
  and .installStrategy == "stage-local-flake"
  and (.installStrategySummary | contains("uploads local flake source"))
  and .installFlake == "path:/tmp/nixos-kexec/flake-source#host"
  and (.commands | length == 10)
  and (.commands | any(.phase == "stage-install" and (.argv | any(contains("tar -C") and contains("flake-source")))))
  and (.commands | any(.phase == "disk-nix-apply" and (.argv | any(. == "-tt"))))
  and (.commands | any(.phase == "disk-nix-apply" and (.argv | any(contains("/run/current-system/sw/bin/disk-nix apply")))))
  and (.commands | all(.phase != "reboot"))
' "$plan_json" >/dev/null

"$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --system "$system" \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --ssh-option Port=2222 \
  --disk-nix-command /run/current-system/sw/bin/disk-nix \
  --no-final-reboot \
  --json >"$plan_json"

jq -e --arg system "$system" '
  .system == $system
  and .installStrategy == "copy-prebuilt-system"
  and (.installStrategySummary | contains("copies a prebuilt system closure"))
  and (.commands | length == 11)
  and (.commands | any(.phase == "nixos-install" and (.argv | any(contains("install mount")))))
  and (.commands | any(.phase == "copy-system" and (.argv | any(contains("nix copy --no-check-sigs --to") and contains("remote-store=local%3Froot%3D%2Fmnt") and contains("NIX_SSHOPTS=")))))
  and (.commands | any(.phase == "nixos-install" and (.argv | any(contains("nixos-install --root /mnt --system") and contains("--no-channel-copy")))))
  and (.commands | all(.phase != "reboot"))
' "$plan_json" >/dev/null

"$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --installer-known-hosts-file "$known_hosts" \
  --host-key "$host_key" \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --disk-nix-command /run/current-system/sw/bin/disk-nix \
  --no-final-reboot \
  --json >"$plan_json"

jq -e --arg host_key "$host_key" --arg host_key_public "$host_key.pub" '
  .hostKey == $host_key
  and .hostKeyPublic == $host_key_public
  and (.installerKnownHostsFiles | length == 1)
  and (.warnings | any(contains("deploy-time secrets")))
  and (.commands | length == 18)
  and (.commands | any(.phase == "stage-install" and (.argv | any(contains("installer-known-hosts-0")))))
  and (.commands | any(.phase == "stage-install" and ((.argv | any(contains("/root/.ssh/known_hosts"))) and (.argv | any(contains("/etc/ssh/ssh_known_hosts"))))))
  and (.commands | any(.phase == "nixos-install" and (.argv | any(contains("install mount")))))
  and (.commands | any(.phase == "stage-host-identity" and (.argv | any(contains("chmod 0600") and contains("ssh_host_ed25519_key")))))
  and (.commands | any(.phase == "stage-host-identity" and (.argv | any(contains("install -o root -g root -m 0600") and contains("/mnt/etc/ssh/ssh_host_ed25519_key")))))
  and (.commands | any(.phase == "stage-host-identity" and (.argv | any(contains("nixos-kexec-git-identity")))))
  and (.commands | any(.phase == "nixos-install" and (.argv | any(contains("GIT_SSH_COMMAND") and contains("nixos-kexec-git-identity")))))
  and (.commands | any(.phase == "nixos-install" and (.argv | any(contains("rm -f /root/.ssh/nixos-kexec-git-identity")))))
  and (.commands | any(.phase == "nixos-install" and (.argv | any(contains("nixos-install --root /mnt --flake") and contains("github:example/flake#host")))))
  and (.commands | all(.phase != "reboot"))
' "$plan_json" >/dev/null

if "$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --host-key-public "$host_key.pub" \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" 2>"$tmpdir/host-key-refusal.err"; then
  echo "plan with --host-key-public and no --host-key unexpectedly succeeded" >&2
  exit 1
fi
grep -F -- '--host-key-public requires --host-key' "$tmpdir/host-key-refusal.err" >/dev/null

if "$bin" run root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" 2>"$tmpdir/run-refusal.err"; then
  echo "run without --execute unexpectedly succeeded" >&2
  exit 1
fi
grep -F 'run refuses to execute without --execute' "$tmpdir/run-refusal.err" >/dev/null

if "$bin" plan 192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" 2>"$tmpdir/target-refusal.err"; then
  echo "plan without SSH user unexpectedly succeeded" >&2
  exit 1
fi
grep -F 'SSH target should include a user' "$tmpdir/target-refusal.err" >/dev/null

if "$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$tmpdir/missing.json" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" 2>"$tmpdir/missing-refusal.err"; then
  echo "plan with missing disk spec unexpectedly succeeded" >&2
  exit 1
fi
grep -F 'disk spec does not exist' "$tmpdir/missing-refusal.err" >/dev/null

if "$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --flake-source "$flake_source" \
  --system "$system" \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" 2>"$tmpdir/strategy-refusal.err"; then
  echo "plan with --system and --flake-source unexpectedly succeeded" >&2
  exit 1
fi
grep -F -- '--system and --flake-source select different install strategies' \
  "$tmpdir/strategy-refusal.err" >/dev/null
