#!/usr/bin/env bash
set -euo pipefail

bin="${NIXOS_KEXEC_BIN:?NIXOS_KEXEC_BIN must point at nixos-kexec}"
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

spec="$tmpdir/disk-nix-install.json"
flake_source="$tmpdir/flake-source"
kernel="$tmpdir/bzImage"
initrd="$tmpdir/initrd"
script="$tmpdir/nixos-kexec.sh"
plan_json="$tmpdir/plan.json"

printf '{"version":1,"apply":{"mode":"install"}}\n' >"$spec"
mkdir -p "$flake_source"
printf '{}\n' >"$flake_source/flake.nix"
printf 'kernel\n' >"$kernel"
printf 'initrd\n' >"$initrd"

"$bin" --help | grep -F 'Deploy NixOS through kexec with disk-nix storage management' >/dev/null
"$bin" completions bash | grep -F 'nixos-kexec' >/dev/null

if [ -n "${NIXOS_KEXEC_EXAMPLES_DIR:-}" ]; then
  "${NIXOS_KEXEC_BASH:-bash}" -n "$NIXOS_KEXEC_EXAMPLES_DIR/install-from-template.sh"
  "${NIXOS_KEXEC_BASH:-bash}" -n "$NIXOS_KEXEC_EXAMPLES_DIR/install-with-preinstalled-disk-nix.sh"
  jq -e '.version == 1' "$NIXOS_KEXEC_EXAMPLES_DIR/specs/simple-root.json" >/dev/null
  jq -e '.version == 1 and .pools.zroot.operation == "create"' \
    "$NIXOS_KEXEC_EXAMPLES_DIR/specs/zfs-encrypted-root.by-id.json" >/dev/null
fi

"$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --ssh-option StrictHostKeyChecking=accept-new \
  --json >"$plan_json"

jq -e '
  .target == "root@192.0.2.10"
  and .flake == "github:example/flake#host"
  and (.commands | length == 9)
  and (.commands | any(.phase == "kexec" and .mutates == true and (.argv | any(contains("kexec -l")))))
  and (.commands | any(.phase == "disk-nix-apply" and (.argv | any(contains("apply --spec")))))
  and (.commands | any(.phase == "nixos-install" and (.argv | any(contains("install nixos")))))
  and (.warnings | any(contains("kexec replaces the running kernel")))
' "$plan_json" >/dev/null

"$bin" script root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --script-out "$script"

test -x "$script"
grep -F 'Generated by nixos-kexec' "$script" >/dev/null
grep -F 'kexec -l /tmp/nixos-kexec/kexec/kernel' "$script" >/dev/null
grep -F 'disk-nix-install.json --probe-current --execute' "$script" >/dev/null
grep -F 'install nixos --spec /tmp/nixos-kexec/disk-nix-install.json' "$script" >/dev/null

"$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --flake-source "$flake_source" \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" \
  --ssh-tty \
  --disk-nix-command /run/current-system/sw/bin/disk-nix \
  --no-final-reboot \
  --json >"$plan_json"

jq -e '
  .diskNixCommand == "/run/current-system/sw/bin/disk-nix"
  and .sshTty == true
  and .installFlake == "path:/tmp/nixos-kexec/flake-source#host"
  and (.commands | length == 9)
  and (.commands | any(.phase == "stage-install" and (.argv | any(contains("tar -C") and contains("flake-source")))))
  and (.commands | any(.phase == "disk-nix-apply" and (.argv | any(. == "-tt"))))
  and (.commands | any(.phase == "disk-nix-apply" and (.argv | any(contains("/run/current-system/sw/bin/disk-nix apply")))))
  and (.commands | all(.phase != "reboot"))
' "$plan_json" >/dev/null

if "$bin" run root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" 2>"$tmpdir/run-refusal.err"; then
  echo "run without --execute unexpectedly succeeded" >&2
  exit 1
fi
grep -F 'run refuses to execute without --execute' "$tmpdir/run-refusal.err" >/dev/null

if "$bin" plan 192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$spec" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" 2>"$tmpdir/target-refusal.err"; then
  echo "plan without SSH user unexpectedly succeeded" >&2
  exit 1
fi
grep -F 'SSH target should include a user' "$tmpdir/target-refusal.err" >/dev/null

if "$bin" plan root@192.0.2.10 \
  --flake github:example/flake#host \
  --disk-spec "$tmpdir/missing.json" \
  --kexec-kernel "$kernel" \
  --kexec-initrd "$initrd" 2>"$tmpdir/missing-refusal.err"; then
  echo "plan with missing disk spec unexpectedly succeeded" >&2
  exit 1
fi
grep -F 'disk spec does not exist' "$tmpdir/missing-refusal.err" >/dev/null
